### ISSUE TITLE
Snowflake ID execution in ekuiper will lose precision

### ISSUE THREAD

**Issue by echils** [lf-edge/ekuiper#3441]
Snowflake ID execution in ekuiper will lose precision

**Environment**:

- eKuiper version (e.g. `1.3.0`):  1.14.0
- Hardware configuration (e.g. `lscpu`): x86_64
- OS (e.g. `cat /etc/os-release`): Debian GNU/Linux 
- Others:

**What happened and what you expected to happen**: 

fix it please!

**How to reproduce it (as minimally and precisely as possible)**:

Enter a snowflake ID in the data source

**Anything else we need to know?**:

**Comment by ngjaying** [comment]
@echils Thanks for rasing this up. We are willing to fix any problems, but before that, we need to know the problem. How to reproduce it. I am not sure this one line explanation can help or not.

**Comment by echils** [comment]
My use case：

1.  Create a kafka source named `root` ，the sample data structures are shown below
   
```
    {
      "createTime": "2024-12-12T14:34:37.516Z",
      "data": {
          "abnormal": false,
          "data": [
          {
              "field": "unit",
              "tag": false,
              "value": "m/s"
          }
          ],
          "definitionId": 1795292668348461056,
          "time": "2024-12-12 14:34:37",
          "value": 0
      },
      "definitionId": 1795292668348461056,
      "messageId": "schedule-1867095692340801536",
      "msg": null,
      "status": 200
    }
```
2. Create a simple rule
```
 select data.definitionId from root
```
3. Create a mqtt sink
4. The mqtt result has lost accuracy
![image](https://github.com/user-attachments/assets/c62a7364-22a1-4cc9-8db1-78d5e26302ed)

**Comment by echils** [comment]
Hi, is there any progress on this issue?

**Comment by Yisaer** [comment]
It's fixed in the https://github.com/lf-edge/ekuiper/pull/3445

You can try the latest master version and add `useInt64ForWholeNumber: true` in the source conf used by the target stream

**Comment by younes199511** [comment]
Hello @ngjaying @Yisaer 

Is it possible to fix this bug in 1.14 version ?

Thank you

**Comment by echils** [comment]
> It's fixed in the [#3445](https://github.com/lf-edge/ekuiper/pull/3445)
> 
> You can try the latest master version and add `useInt64ForWholeNumber: true` in the source conf used by the target stream

When I built ekuiper using the docker image `lfedge/ekuiper: v2.1.1-slim-python`, I found that the precision loss problem still existed. How to configure `useInt64ForWholeNumber: true` when using docker? Can you provide examples

**Comment by Yisaer** [comment]
@echils  Here is one example I tested by the mqtt source 

step 1, create a new source conf

```sh
POST /metadata/sources/mqtt/confKeys/test2
{
     "server": "tcp://127.0.0.1:1883",
     "protocolVersion": "3.1.1",
     "useInt64ForWholeNumber": true
}
```

step 2, create a new stream using the new conf
```sh
POST /streams
{
    "sql":" CREATE STREAM test2  ()       WITH (CONF_KEY=\"test2\",DATASOURCE=\"/yisa/data\");"
}
```

step 3, create a new rule using the new stream
```sh
POST /rules
{
    "id": "rule2",
    "sql": "SELECT id from test2",
    "actions": [
        {
            "log": {
            }
        }
    ],
    "options" :{
    }
}
```

Sending a message throught mqtt
```json
{
  "id":1795292668348461056
}
```
then log is 
```sh
time="2025-04-11T10:00:41+08:00" level=info msg="sink result for rule rule2: [{\"id\":1795292668348461056}]" file="sink/log_sink.go:32" rule=rule2
```

**Comment by echils** [comment]
Thank you very much @Yisaer , after I clean and start the configuration again, the accuracy problem is resolved.  The previous configuration update did not take effect, maybe I did not update the source and rule again
