### ISSUE TITLE
validate golang portable plugins timeout

### ISSUE THREAD

**Issue by echils** [lf-edge/ekuiper#3784]
When ekuiper loads the golang portable plugin and runs for some time, ekuiper will trigger the error "error: validate function xxxx error: time out, plugin xxxx status running, message: ."

**Environment**:

- eKuiper version (e.g. `1.3.0`): v2.2.0
- Hardware configuration (e.g. `lscpu`):

<img width="763" height="641" alt="Image" src="https://github.com/user-attachments/assets/b0e8468f-ac4d-48fd-899c-c49a0988b8ae" />

- OS (e.g. `cat /etc/os-release`):

<img width="491" height="166" alt="Image" src="https://github.com/user-attachments/assets/7769ee12-e357-48cb-9f48-5ced45faccc3" />

- Others:

When ekuiper loads the golang portable plugin and runs for some time, ekuiper will trigger the error "error: validate function value_dvt error: time out, plugin threshold_judge status running, message: .", in this error message, threshold_judge is the golang plugin compilation file, and value_dvt is one of the functions in the plugin。

At present, I'm not sure if it will take a long time to reproduce this issue. I got the error message in the ekuiper interface response when adding the rule. But it is certain that I have encountered this problem many times, and each time I need to restart ekuiper to restore it to normal

**Comment by Yisaer** [comment]
@echils  please provide the golang protable plugin so we can reproduce the issue.

**Comment by echils** [comment]
> [@echils](https://github.com/echils) please provide the golang protable plugin so we can reproduce the issue.

[threshold_judge_golang_amd.zip](https://github.com/user-attachments/files/21366738/threshold_judge_golang_amd.zip)

**Comment by Yisaer** [comment]
@echils  Please provide the golang portable plugin builtin macos system.

Also you can try the following way to solve the issue:

1. make sure the plugin is running by query the following api, find the process id and ensure the process is still running.

```
GET /plugins/portables/{name}/status
```

2. enlarge the portable plugin response timeout in `kuiper.yaml`:


```yaml
portable:
  initTimeout: 60s
  sendTimeout: 5s (enlarge it to 10s)
  recvTimeout: 5s (enlarge it to 10s)
```

**Comment by echils** [comment]
I don't understand the meaning of the sentence "Please provide the golang portable plugin builtin macos system"

I guess you want me to provide a development environment for the goloang portable plugin

<img width="884" height="368" alt="Image" src="https://github.com/user-attachments/assets/b3048af2-b114-4f6e-a1a9-86265d1ac061" />

<img width="655" height="370" alt="Image" src="https://github.com/user-attachments/assets/746c4556-f00f-441c-80ca-38d8013d45ae" />

<img width="604" height="169" alt="Image" src="https://github.com/user-attachments/assets/c27724de-8017-441b-bb25-5a6ed0f936ae" />

**Comment by ngjaying** [comment]
This issue has been fixed by PR #3965 (commit e96d46af).

The Go SDK function channel now includes a 5-second receive timeout, which prevents the socket from becoming stale during idle periods. The fix adds `OptionRecvDeadline` to the function channel and handles timeout by continuing the loop (matching the pattern used in sink/source implementations).

The fix is available in versions after v2.3.0.

**Comment by echils** [comment]
This issue still persists in version 2.4.0. I have tested that not only the portable plugins developed in Go will behave this way, but also the Python plugins will encounter the same problem.
https://github.com/lf-edge/ekuiper/issues/4077
logs:
`
"cannot find the native plugin value_gt in path: invalid symbol name value_gt: not exist" file="native/manager.go:824"
time="2026-08-05T18:33:43+08:00" level=debug msg="cannot find the native plugin value_gt in path: invalid symbol name value_gt: not exist" file="native/manager.go:824"
time="2026-08-05T18:33:43+08:00" level=debug msg="send request: {\"func\":\"Validate\",\"arg\":[{\"OP\":29,\"LHS\":{\"StreamName\":\"root\",\"Name\":\"data\",\"HasIndex\":false,\"SourceIndex\":0,\"Index\":0},\"RHS\":{\"Name\":\"value\"}},{\"Val\":10}]}" file="runtime/connection.go:151"
time="2026-08-05T18:33:43+08:00" level=debug msg="send request protestate error incorrect protocol state" file="runtime/connection.go:156"
time="2026-08-05T18:33:53+08:00" level=error msg="invalid rule json: Parse SQL SELECT rule_id() AS ruleId, bind.indicator_id AS tsdataId, root.data.value AS value, root.data.unit AS unit, root.data.time AS time , bind.indicator_data_type AS tsdataDataType, bind.equipment_id as eventEquipmentId,bind.equipment_name as eventEquipmentName,bind.property_id as eventPropertyId,bind.property_id as eventPropertyName , (value_gt(root.data.value,10) OR value_gt(root.data.value,20)) as abnormal, \"EXCEED_LIMIT_ALARM\" as eventCode, CASE WHEN value_gt(root.data.value,10)=true THEN 2 WHEN value_gt(root.data.value,20)=true THEN 3 ELSE 1 END as alarmLevel FROM root INNER JOIN bind ON root.data.definitionId = bind.indicator_id WHERE bind.equipment_id = 2065341573649571840 AND bind.property_id = \"GKJCKGWD\" AND bind.indicator_data_type =\"NUMERIC\"  error: validate function value_gt error: time out, plugin threshold_judge status running, message: ." file="server/rest.go:92"
time="2026-08-05T18:33:53+08:00" level=debug msg="triggered by timeout" file="node/window_op.go:468" rule=2084946409282342918
`
